package P2PCommon;


/**
* P2PCommon/ServerServantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Sunday, February 28, 2016 9:02:18 o'clock PM PST
*/

abstract public class ServerServantHelper
{
  private static String  _id = "IDL:P2PCommon/ServerServant:1.0";

  public static void insert (org.omg.CORBA.Any a, P2PCommon.ServerServant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static P2PCommon.ServerServant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (P2PCommon.ServerServantHelper.id (), "ServerServant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static P2PCommon.ServerServant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerServantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, P2PCommon.ServerServant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static P2PCommon.ServerServant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P2PCommon.ServerServant)
      return (P2PCommon.ServerServant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      P2PCommon._ServerServantStub stub = new P2PCommon._ServerServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static P2PCommon.ServerServant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P2PCommon.ServerServant)
      return (P2PCommon.ServerServant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      P2PCommon._ServerServantStub stub = new P2PCommon._ServerServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
