package P2PCommon;

/**
* P2PCommon/ServerServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Sunday, February 28, 2016 9:02:18 o'clock PM PST
*/

public final class ServerServantHolder implements org.omg.CORBA.portable.Streamable
{
  public P2PCommon.ServerServant value = null;

  public ServerServantHolder ()
  {
  }

  public ServerServantHolder (P2PCommon.ServerServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P2PCommon.ServerServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    P2PCommon.ServerServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P2PCommon.ServerServantHelper.type ();
  }

}
