package P2PCommon;


/**
* P2PCommon/ServerServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Sunday, February 28, 2016 9:02:18 o'clock PM PST
*/

public interface ServerServantOperations 
{
  String sayHello ();
  boolean authorize (String username, String password);
  void updateAddress (String username, String ip, int port);
  void share (String username, String filename);
  boolean isShared (String username, String filename);
  String[] getSharedFiles (String username);
  void stopShare (String username, String filename);
  String[] findFile (String username, String filename);
} // interface ServerServantOperations
